[project]
src = "src"
out = "out"
dot_env = ".env"

[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337

[networks.sepolia]
url = "https://ethereum-sepolia-rpc.publicnode.com"
chain_id = 11155111

[networks.mainnet]
url = "https://eth.merkle.io/"
chain_id = 1

[networks.gnosis]
url = "https://rpc.gnosischain.com"
chain_id = 100

[networks.base]
url = "https://base.llamarpc.com"
chain_id = 8453

[networks.arbitrum]
url = "https://arbitrum.llamarpc.com"
chain_id = 42161

[networks.scroll]
url = "https://1rpc.io/scroll"
chain_id = 534352

[networks.polygon]
url = "https://polygon.llamarpc.com"
chain_id = 137

[networks.op]
url = "https://optimism.llamarpc.com"
chain_id = 10


[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
